### ISSUE TITLE
Missing Prettier configuration?

### ISSUE THREAD

**Issue by jscheid** [sindresorhus/issue-regex#12]
It seems that code style is enforced by `xo` and it uses `prettier`, and sets a version (2.6.0) for it in `yarn.lock`. But running `yarn && yarn prettier --write '*.js' && yarn test` in this repository produces [errors](https://gist.github.com/jscheid/2327647745ee9901fd56a06fc54ab73c). Is it perhaps expecting a non-default Prettier configuration? If so, it would be good to add that to the repository because otherwise it's extremely annoying to have to manually keep the linter happy.

**Comment by sindresorhus** [comment]
I'm not using Prettier. XO support Prettier if you use it, but I don't.
