### ISSUE TITLE
Linking to issues with GH- and full URL syntax

### ISSUE THREAD

**Issue by jscheid** [sindresorhus/issue-regex#15]
There are [more ways to reference issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests):
- `GH-14`: GH-14
- `https://github.com/sindresorhus/issue-regex/issues/14`: https://github.com/sindresorhus/issue-regex/issues/14

Arguably, these should be recognized as well. For the second one, there should probably be a configuration option to support on-premise (enterprise) installations of GitHub.

**Comment by jscheid** [comment]
The boundary for GH-style links appears to be just `\w`

foo-GH-14
foo:GH-14
foo/GH-14
foo@GH-14
foo%GH-14
foo,GH-14
foo.GH-14
foo_GH-14
fooGH-14
123GH-14
GH-14-foo
GH-14:foo
GH-14/foo
GH-14@foo
GH-14%foo
GH-14,foo
GH-14.foo
GH-14_foo
GH-14foo

Unlike GH-links, URLs _can_ follow an underscore or a digit, but can't be followed by a dot. Interestingly, anything attached to the end of the URL gets hidden (i.e. should be considered part of the match):

foo-https://github.com/sindresorhus/issue-regex/issues/14
foo:https://github.com/sindresorhus/issue-regex/issues/14
foo/https://github.com/sindresorhus/issue-regex/issues/14
foo@https://github.com/sindresorhus/issue-regex/issues/14
foo%https://github.com/sindresorhus/issue-regex/issues/14
foo,https://github.com/sindresorhus/issue-regex/issues/14
foo.https://github.com/sindresorhus/issue-regex/issues/14
foo_https://github.com/sindresorhus/issue-regex/issues/14
foohttps://github.com/sindresorhus/issue-regex/issues/14
123https://github.com/sindresorhus/issue-regex/issues/14
https://github.com/sindresorhus/issue-regex/issues/14-foo
https://github.com/sindresorhus/issue-regex/issues/14:foo
https://github.com/sindresorhus/issue-regex/issues/14/foo
https://github.com/sindresorhus/issue-regex/issues/14@foo
https://github.com/sindresorhus/issue-regex/issues/14%foo
https://github.com/sindresorhus/issue-regex/issues/14,foo
https://github.com/sindresorhus/issue-regex/issues/14.foo
https://github.com/sindresorhus/issue-regex/issues/14_foo
https://github.com/sindresorhus/issue-regex/issues/14foo

**Comment by jscheid** [comment]
I'm not sure what's happening here, a bug maybe? It doesn't look intentional so perhaps best to ignore it.

`sindresorhus/issue-regex/issues/14`: sindresorhus/issue-regex/issues/14

**Comment by sindresorhus** [comment]
This package does not specifically target GitHub. The syntax it targets works on GitLab and many other services.

I'm happy to support GH and links, but both should be opt-in through options.

**Comment by jscheid** [comment]
I should have guessed by the name of this repository but it's still surprising to hear that. For example, GitLab [supports](https://docs.gitlab.com/ee/user/markdown.html#gitlab-specific-references) `repo#issueNumber` references which aren't covered here.

Anyway, I only need GitHub-specific references myself at this time, but happy to draw the distinction between generic and GitHub-specific regex.

**Comment by EmileSonneveld** [comment]
Gitlab seems to support refering to a ticket by URL too: 
![image](https://github.com/sindresorhus/issue-regex/assets/2298426/7e50ae20-2551-4dff-9a2d-066b25ca17e2)
Could be tough to create a mega-regex that supports all formats tough. If I find some time today, I'll make a Pull Request.

An example commit message here: https://gitlab.com/emillo108/test/-/commit/b55edf9992466c9c6d35972c64a8a9c09952bc49

**Comment by EmileSonneveld** [comment]
Hmm, the solution I came up with is good for personal use, but not to commit here.
```javascript
return /(?<!\w)(?:(?:(?:(?<organization>[a-z\d](?:[a-z\d-]{0,37}[a-z\d])?)\/)?(?<repository>[\w.-]{1,100}))?(?<!(?:\/\.{1,2}))#(?<issueNumber>[1-9]\d{0,9})|(?:https:\/\/gitlab\.com\/(?<organizationURL>[a-z\d](?:[a-z\d-]{0,37}[a-z\d])?)\/(?<repositoryURL>[\w.-]{1,100})\/-\/issues\/(?<issueNumberURL>[1-9]\d{0,9})))/gi;```
